Metrics/LineLength:
  Max: 120

AllCops:
  TargetRubyVersion: 2.4.3
  Exclude:
    - 'db/**/*.rb'

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'spec/**/*.rb'

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false
