version: '3'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: 'hqtrust_core_api'
      POSTGRES_PASSWORD: '86RRfQkPw93NYDyX'
    ports:
      - '5432:5432'
  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - /data
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
    environment:
      REDIS_URL: 'redis://redis'
    env_file:
      - development.env
  api:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: 'redis://redis'
      WHITELISTED_URLS: 'http://localhost:3001,https://app.dev.hqfinanz.de'
    env_file:
      - development.env
