# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  aws_ses_access_key_id: <%= ENV["AWS_SES_ACCESS_KEY_ID"] %>
  aws_ses_secret_access_key: <%= ENV["AWS_SES_SECRET_ACCESS_KEY"] %>
  aws_s3_access_key_id: <%= ENV["AWS_S3_ACCESS_KEY_ID"] %>
  aws_s3_secret_access_key: <%= ENV["AWS_S3_SECRET_ACCESS_KEY"] %>
  mailjet_api_key: <%= ENV["MAILJET_API_KEY"] %>
  mailjet_secret_key: <%= ENV["MAILJET_SECRET_KEY"] %>

# Environmental secrets are only available for that specific environment.

integration:
  secret_key_base: 6c390e905b8bf1a29b2ff0409f7f910c4eabaff0124f7057a54383a763ca6b90503272b080041acde6a69292ea7f93427eb9c66e109e3b1238d88c3f2d8c8111
  devise_jwt_secret_key: 7f9c9ecd61e4eacd5528c838bc46b043553f23450e73a40169b526133592f0c13fd60d32d22cc19f07bd90461836cbcd3b9a290526fddf9bc8c8c011758285b5
  host_url: 'localhost:3000'

development:
  secret_key_base: 6c390e905b8bf1a29b2ff0409f7f910c4eabaff0124f7057a54383a763ca6b90503272b080041acde6a69292ea7f93427eb9c66e109e3b1238d88c3f2d8c8111
  devise_jwt_secret_key: 7f9c9ecd61e4eacd5528c838bc46b043553f23450e73a40169b526133592f0c13fd60d32d22cc19f07bd90461836cbcd3b9a290526fddf9bc8c8c011758285b5
  host_url: 'localhost:3000'

test:
  secret_key_base: a80bcaa689d2f848b88729a537f5398ad17d47c202e01d7d06e4865dceff0f88fb6bd3a357bab9acea4ed7e55ba223b902f30ffdcbf576b93a7b41d28ba20e2a
  devise_jwt_secret_key: 0e4e88460b5827ecd775367934791e13cee7111f2f49c831fc06e30c062b0e69173b83071f82eedd553dccf8205233a3b5c7d2ccb2b79404facb415cb9c3a09d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_jwt_secret_key: <%= ENV["DEVISE_JWT_SECRET_KEY"] %>
  sentry_url: <%= ENV["SENTRY_URL"] %>
  logentries_token: <%= ENV["LOGENTRIES_TOKEN"] %>
  host_url: <%= ENV["HOST_URL"] %>
