class MigrateOrganizationMemberRoles < ActiveRecord::Migration[5.2]
  ROLES = {
    'Gesellschaft (GF)' => :managing_director,
    'Gesellschafter' => :shareholder,
    'Gesellschaft' => :shareholder,
    'Mandant (Rechtsanwalt)' => :mandate_lawyer,
    'Mandant (Steuerberater)' => :mandate_tax_advisor,
    'Director' => :director,
    'Arbeitgeber' => :employee,
    'Kunde (Vermögensverwaltung)' => :client_wealth_management,
    'wirtschaftlicher Eigentümer' => :beneficial_owner,
    'HQT-FO-Mandant' => :hqt_contact,
    'HQT-Prospect' => :hqt_contact,
    'HQT-Kontakt' => :hqt_contact,
    'Vermögensverwalter' => :client_wealth_management,
    'Vorstand' => :chairman,
    'Vorgesetzter' => :supervisor,
    'Makler (Versicherung)' => :broker_insurance,
    'Berater (Bank)' => :consultant_bank,
    'Stiftung' => :benefactor,
    'Kontakt' => :contact,
    'Kunde (Bank)' => :client_bank,
    'Verwalter (Immobilienverwaltung)' => :custodian_real_estate,
    'Beteiligungsgesellschaft' => :shareholder,
    'Steuerberater' => :mandate_tax_advisor,
    'Makler (Immobilien)' => :broker_real_estate,
    'Gesellschaft (Beirat)' => :advisor,
    'HQT-Mitarbeiter' => :hqt_contact,
    'Assistent(in)' => :assistant,
    'Gesellschafter (GF)' => :managing_partner,
    'GF' => :managing_director,
    'Mandat' => :mandate,
    'Geschäftsführer' => :managing_director,
    'Account Manager RVK' => :contact_asset_manager,
    'Mitarbeiter' => :employee,
    'AI Client Services' => :customer_consultant,
    'Prokurist' => :procurator,
    'Assistentin der Geschäftsführung' => :assistant,
    'Steuerberater/Wirtschaftsprüfer' => :mandate_tax_advisor,
    'Leiter Finanzen' => :cfo,
    'Persönlich haftender Gesellschafter' => :general_partner,
    'Portfoliomanager' => :portfolio_manager,
    'Alternative Investments' => :portfolio_manager_alternative_investments,
    'Grüdungsgesellschafter' => :shareholder,
    'Mitarbeiter Immobilien und Steuern' => :employee,
    'Gesellschafterin' => :shareholder,
    'Ansprechpartner bei BDO' => :contact_contractor,
    'RM Bank' => :consultant_bank,
    'CIO' => :cio,
    'Gesellschafter Geschäftsführer' => :managing_partner,
    'Family Officer' => :family_officer,
    'Geschäftsführerin' => :managing_director,
    'Kommanditisten' => :limited_partner,
    'Kommanditistin' => :limited_partner,
    'Verwaltungsrat' => :administrative_board_member,
    'Berater' => :consultant,
    'Kundenbetreuer' => :contact_asset_manager,
    'Fund Oversight PM' => :portfolio_manager,
    'Member of IC' => :member_investment_committee,
    'Direktor' => :director,
    'Steuerberaterin' => :mandate_tax_advisor,
    'Beirat' => :advisor,
    'Investment Manager' => :investment_manager,
    'Gesellschafter/Geschäftsführer' => :managing_partner,
    'Ansprechpartnerr Depotrtbank' => :contact_depot_bank,
    'CEO' => :ceo,
    'Relationship Management Investmentfonds' => :contact_asset_manager,
    'Assistenz' => :assistant,
    'Sprecher der Geschäftsführung' => :spokesperson_of_the_board,
    'Analyst' => :analyst,
    'wirtschaftlich Berechtigte' => :beneficiary,
    'Eigentümer' => :beneficial_owner,
    'GF Gesellschafter' => :managing_partner,
    'Buchhalter' => :bookkeeper,
    'Geschäftsführer Komplementärin' => :managing_general_partner,
    'Geschäftsführer Komplementär' => :managing_general_partner
  }

  def change
    ROLES.each do |key, value|
      OrganizationMember.where(role: key).update_all(role: value)
    end
  end
end
